### ISSUE TITLE
Almacenes -->Recep. depósito: la carga de Fecha de vencimiento es incómoda

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#11]
ID del bug: ALM-RPD-01-01

Sugerencia: se podría indicar por dónde cargar la fecha o revisar el ingreso del dato en la tabla

Pasos para la reproducción:
1- En módulo almacenes, click en ABM Recep. depósitos
2- Completar los datos correspondientes y hacer click en "Guardar"

![CAPT7](https://user-images.githubusercontent.com/88331456/131029605-6f130301-8e73-404b-b1c8-c2fa1095064a.png)

![CAPT6](https://user-images.githubusercontent.com/88331456/131030078-304a99ed-ad06-494c-827f-c4b80cebd715.png)

**Comment by aalfaro-trazalog** [comment]
Una sugerencia, en la misma tabla en lugar del icono de editar, que haya un icono "+" asi el usuario se puede dar cuenta de que debe adicionar datos
