### ISSUE TITLE
Almacenes-->Artículos: falla al eliminar un artículo

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#114]
Ambiente de Test - v2.2.15

**Descripción:**
Al presionar el botón eliminar de un artículo el sistema muestra un cartel de eliminado con éxito, pero continúa figurando en la tabla. Lo correspondiente sería que el sistema elimine de los registros el artículo seleccionado.
Nota: se agrega un video con audio.

https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/3b904b30-d589-4960-b1b2-331af8339be6

**Pasos a seguir:**
1. En el módulo Almacenes
2. Clic en Artículos
3. Clic en el botón "Eliminar"
4. Clic en el botón "Si, Eliminar artículo"
5. Clic en el botón Ok
6. Buscar el artículo eliminado

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.15

**Comment by floto-trazalog** [comment]
Vuelve a fallar en v2.2.17

**Comment by floto-trazalog** [comment]
Continúa fallando en v2.2.20

**Comment by jfernandez-trazalog** [comment]
Roge Sanchez.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.7

**Comment by fhernandez-trazalog** [comment]
#114: Resuelto exitosamente. Se pueden eliminar artículos y confiar en la notificación recibida al hacerlo
