### ISSUE TITLE
Almacenes-->Stock: no carga la pantalla

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#115]
Ambiente test - v2.1.15

**Descripción:**
Cuando completamos los campos del filtro en la pantalla de Stock, el sistema queda en una recarga infinita

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/639065fa-d612-4efa-8e85-faa9f309630b)

**Pasos a seguir:**
1. En Almacenes
2. Clic en Stock
3. Cargar los siguientes campos:
 Establecimiento: Establecimiento 
 Tipo Depósito: Productivo
 Depósito: Deposiito Prueba
 Recipiente: REC_prueba_1
 Tipo de artículo: Final
 Fecha: 27/04/2022 al 03710/2023
 Artículo: PP0013
 Botón "Filtrar"

**Comment by gnicolia-trazalog** [comment]
Solucionado en V 2.2.17
