### ISSUE TITLE
Almacenes-->Ajuste de stock: que permita guardar el ajuste de stock

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#120]
Ambiente Test - v2.2.17

**Descripción:**
Al seleccionar un artículo con lote asociado el sistema no reconoce que sesa del tipo "materia prima" y lo correspondiente es que lo tome como materia prima
Se trata del artículo: ppp001

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/67f28ece-b3f6-481f-ad47-17863901d27f)

**Pasos a seguir:**
1. En Almacenes
2. En Ajuste de stock
3. Completar los campos obligatorios
4. Clic en botón "guardar"

**Comment by jfernandez-trazalog** [comment]
Roge Sanchez.

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.20
