### ISSUE TITLE
Almacenes-->Ajuste Stock: que recupere el dato de unidad de medida 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#124]
Ambiente Producción - v2.2.18.1  
URL: https://cloudtrazalog.com/traz-comp-dnato/main/login
usr: responsablealmacen@adl.com
pass: 12345

**Descripción:**
Al seleccionar la opción "Devolución" y completar los campos obligatorios, el sistema recupera la unidad de medida = "null" y, lo correspondiente sería que recupere la unidad con la que está cargada en la tabla de artículos.

 
![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/c0c69fa2-d493-4271-86fe-5ea8c50da611)

**Pasos a seguir:**

1. Almacenes
2. Ajuste

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.20
