### ISSUE TITLE
Almacenes-->Stock: que muestre los artículos con stock mayor a 0

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#128]
Ambiente Test - v2.2.20

**Descripción:**
En la tabla de stock figuran algunos registros con valores negativos, lo correspondiente sería añadir una restricción en el instante del movimiento de stock para notificar al usuario que no hay stock

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/4c808c90-fe08-4589-a8ef-81c366f534d7)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by fhernandez-trazalog** [comment]
Siguen apareciendo los artículos con stock menor a 0. Sin embargo, en la prueba efectivamente alerta que el stock es negativo cuando se quiere realizar una entrega, además de detallar los depósitos.
