### ISSUE TITLE
Almacenes-->Recepción de materiales: que la pantalla recupere los campos de precios

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#129]
Ambiente DEMO - v2.2.20

**Descripción:**
 Al completar la recepción de materiales, faltan campos en el formulario _Detalle de recepción_ 
* Precio Unit. (Pesos) *:
* P. Total (Pesos):
* Precio Unit. (Dolar)* :
* P. Total (Dolar):

y que luego, esos datos serán usados en otras pantallas. Desde el ambiente Test el sistema recupera el formulario correctamente.

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/d8909fc2-a6f3-4cee-acf4-952bb56ef636)

**Pasos a reproducir:**
1. En Almacenes
2. Clic en "Recepción de materiales"
3. Clic en el botón "Agregar"

**Impacto:**
Al quedar incompleto el formulario el sistema no logra sincronizar los datos con la pantalla de Almacenes>>Stock Valorizado, quedando la tabla de éste, vacía.

**Resultado esperado:**
Que figuren los campos de los procios para que el sistema tome dichos datos y grabe el registro en la tabla de Stock Valorizado.
Debería verse de esta manera: (img de Ambiente Test v2.2.20)

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/daedd51c-aaf1-4f1c-a47f-d6d634e4d4cd)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.7

**Comment by fhernandez-trazalog** [comment]
Se agregaron los campos solicitados al formulario, por lo que quedó resuelto.
