### ISSUE TITLE
Mis Tareas-->en Tarea "Pedidos Materiales": que cada encargado visualice su respectivo depósito asociado

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#130]
Ambiente de Test - v2.2.20

**Descripción:**
En la pantalla de "Mis tareas" cuando se gestiona la "Entrega de materiales", el responsable de almacen puede ver todos los depósitos y lo correspondiente sería que el sistema recupere solo los depósitos que se encuentran asociados al usuario que se encuentra logueado.

**Detalles adicionales:**
**Importante:** los encargados se asignan desde el menú Configuraciones-->ABM Establecimientos-->botón de acción "Depósito"

**Respuesta esperada:**
En Mis tareas-->Ped. Materiales: que el usuario solo vea, en el listado de registros, sus depósitos a cargo.

**Pasos para reproducir:**
1. En "Mis Tareas"
2. Clic en una tarea llamada "Ped. Materiales"
3. Clic en el botón "Relaizar entrega"
4. Clic en el botón **+ (más)** ubicado a la derecha de la tabla inferior

https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/634be83e-9368-41c4-a117-8ff6cf1cb61f

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by fhernandez-trazalog** [comment]
Se puede visualizar en la tarea "Pedidos Materiales" los respectivos depósitos asociados, así mismo configurarlos desde el ABM.
