### ISSUE TITLE
SOPORTE-->Almacenes-->Stock: que la tabla filtre por depósito segun el encargado logueado   

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#132]
Ambiente Test - v2.2.20

Descripción: 
actualmente, el usuario responsable del almacen puede visualizar el stock de todos los depósitos de almacenes, y se requiere que cada encargado vea los depósitos de los cuales están a su cargo, salvo que se le asignen todos los depósitos, en ese caso si tendrá acceso.

_Se agrega un video -activar audio-

https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/03e65c35-e2e7-4ddc-93a3-e05098543806

**Comment by floto-trazalog** [comment]
Se baja prioridad, porque actualm no se está usando el módulo

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.7

**Comment by fhernandez-trazalog** [comment]
El usuario puede ver de acuerdo a los permisos establecidos en la configuración.
