### ISSUE TITLE
Almacenes-->Ajuste de stock: se congela el cartel "sin lotes"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#133]
Ambiente test - v2.3.7

**Descripción:**
Cuando se desea registrar una entrada / salida seleccionando un depósito que no tiene lotes asociados al artículo, eventualemente, se traba el cartel "Sin lotes" al cambiar de depósito con lotes asociados.
Se adjunta un video con audio. 

https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/fe1b552c-7884-4782-a68f-25015a8fc8cc

**Resultado esperado:**
Que el cartel del campo "Lote" se actualice recuperando los lotes asociados. Siempre y cuando el usuario sea encargado de dicho depósito. (se deja un video -activar audio-)

https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/2c24c151-3d12-4bf6-b2ad-286cb0f235b0

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.10
