### ISSUE TITLE
Almacenes-->Stock: agregar una notificación de aviso al usuario que no tiene depósitos asignados

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#134]
Ambiente Test - v2.3.7

**Recomendación:**
Al ingresar en el menú Stock, que el sistema informe al usuario a traves de una ventana de aviso que su usuario aún no se encuentra con depósitos asignados. Se deja la pantalla comprometida y la notificación sugerida

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/e590d3e9-a709-4f00-8c7d-ef23d514b732)

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/3ed9e98f-c8c3-441b-8706-2818372c6979)

**Pasos a reproducir:**
1. En el menú Almacenes
2. Clic en Stock

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.11
