### ISSUE TITLE
Stock-->Filtro: que recupere únicamente los depósitos de los que el user es encargado

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#145]
Ambiente Test - v2.4.1

**Descripción:**
Desde el user jperez@prueba.com se verifica que "Pechugas Laru" es encargado del depósito "Depósito de entrada" _se muestra en la imagen:_

![image](https://github.com/user-attachments/assets/4064a0f3-437a-4066-8d5e-e187c8261384)

Al ingresar con el user pechugaslaru@gmail.com en la interfaz de **Stock,** completar los campos (Fecha Desde, Fecha Hasta, Establecimiento y Tipo Depósito) y filtrar se observa que no filtra correctamente, puesto que recupera el stock de otros depósitos de los cuales no es encargado.

https://github.com/user-attachments/assets/4d7b21f6-8ed1-4570-b4f9-c845b9a39d9f

**Pasos a reproducir:**
1. En el menú Almacenes
2. Ir a la opción de Stock
3. Completar los campos: _Fecha Desde, Fecha Hasta, Establecimiento y Tipo Depósito_
4. Clic en el botón "Filtrar" 

**Resultado esperado:**
Que al ingresar en la pantalla de Stock, el usurio SOLO tenga acceso a la información del stock de los depósitos que este es encargado. Y si no es encargado de ningún depósito muestre un alert con un mensaje: "Ops! No posee depósitos asignados. Comunicarse con el administrador." 

![image](https://github.com/user-attachments/assets/17bd76d4-c180-4f53-9bc6-05b655814aea)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.2
