### ISSUE TITLE
Salida depósito-->Modal remito & vista previa de impresión: alinear y ajustar la tabla de artículos 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#146]
Ambiente Test - v2.4.1

**Descripción:**
Se recomienda ajustar el ancho de la columna "Cantidad" y alinear a izquierda los datos "Cantidad" y "Depósito orig." de la tabla

![image](https://github.com/user-attachments/assets/6aa9e539-70fb-4cb7-a36f-725ed956d26a)

![image](https://github.com/user-attachments/assets/de79157a-83cd-4fb8-b567-3f072493a1cb)

Resultado esperado:

![image](https://github.com/user-attachments/assets/99223a54-008e-49ee-a747-73dd8b24a93a)

**Pasos a reproducir:**
1. En el menú Almacenes
2. Clic en la opción "Salida depósito"
3. Completar los campos obligatorios
4. Clic en el botón "Agregar"
5. Clic en el botón "Guardar"
6. Clic en el botón "Imprimir"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.5
