### ISSUE TITLE
Almacenes-->Recep. Depósito: agregar el nombre del depósito

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#147]
Ambiente Test - v2.4.3

**Descripción:**
Al realizar el movimiento de un depósito a otro el usuario no tiene registro de los IDs de cada depósito del sistema y al recuperar los datos de una salida de un artículo el sistema muestra en el detalle el Nro de ID del depósito y es confuso para el usuario puesto que no manipulan esta información. Lo conveniente sería agregar el nombre del depósito al lado del ID.

https://github.com/user-attachments/assets/1707021a-03cc-45bc-a5b3-6b77afdc1648

**Pasos a reproducir:**

1. En el menú Almacenes
2. Ir a Recep. Depósito
3. Completar los campos (Establecimiento receptor, Depósito receptor)
4. Clic en el botón "Buscar"

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en test v2.4.5
