### ISSUE TITLE
TICA-->Recepción Depósito: falla al recibir 2 artículos en un mismo movimiento

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#148]
Ambiente Test - v2.4.3

**Descripción:**
Cuano se realiza un movimiento de salida y recepción de un depósito a otro con 2 artículos diferentes el sistema solo está mostrando el stock del 2do artículo de los registros ingresados

Se deja captura del stock previo al movimiento con el artículo CAS-001 - Casco de seguridad 01

![image](https://github.com/user-attachments/assets/cf3473da-9290-448f-86d0-efff15a28af7)

Se deja captura del stock previo al movimiento con el artículo CAS-002 - Casco de seguridad 02

![image](https://github.com/user-attachments/assets/422c8b9a-7237-4de5-9578-f33da4d72e9c)

Luego, se realiza la salida del depósito: **Depósito de entrada** hacia el depósito: **Para reciclar**
CAS-001 - cant.=5
CAS-002 - cant.=1

Se deja el video completo en este [enlace](https://drive.google.com/file/d/1gRUF4CPXYAJ3M8tSG14aeeb9QF7252zM/view?usp=drive_link)
Y la parte 2, haciendo clic [aquí](https://drive.google.com/file/d/1xrszvcsh1dHE1_24mvnFn9mJuDNvFHjw/view?usp=drive_link)

**Pasos a reproducir:**
1. En el menú Almacenes
2. Clic en Salida depósito
3. Completar los campos obligatorios, cargar el artículo: CAS-001
4. Clic en "Agregar"
5. Repetir paso 3 y 4)
6. Clic en el botón "Guardar"
7. Ir a "Recep Depósito"
8. Completar los campos "Establecimiento receptor" y "Depósito receptor"
9. Clic en "Buscar"
10. En _Productos a descargar_
11. Completar el campo "C. Recepción"
12. Clic en "Guardar"
13. Revisar en Stock

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado

**Comment by floto-trazalog** [comment]
Se re-abre, sucede en producción v2.4.3

**Comment by floto-trazalog** [comment]
Se cierra versión 2.4.6.2
