### ISSUE TITLE
Almacenes-->Salida Depósito: errores de ortografía

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#15]
Ambiente Test / Yudica

**Descripción:**
Agregar la tilde en las siguientes palabras: Depósito, número, opción, código, artículo y descripción.

**Pasos para reproducir:**
1 - En módulo Almacenes dar click en ABM Salida Depósito

![ALM-SLD-1](https://user-images.githubusercontent.com/88331456/134933831-1d7b08ca-e5b6-430b-ba26-530b5524862b.jpg)
![ALM-SLD-2](https://user-images.githubusercontent.com/88331456/134932080-c827aa68-a6be-47b3-bb0c-6b82932c6011.jpg)

**Comment by aalfaro-trazalog** [comment]
@KevinMarchan faltaron algunos acentos 
![image](https://user-images.githubusercontent.com/87376576/138339498-8a4a1087-9ca7-4e86-8e55-9aa1b14dd51a.png)

**Comment by smustafa-trazalog** [comment]
Se completaron las sugerencias
version v1.5.38
![image](https://user-images.githubusercontent.com/98842352/155593329-55cc3a57-d17d-46ec-baad-273c75617aa0.png)

![image](https://user-images.githubusercontent.com/98842352/155593424-862933ef-4d95-4979-bd20-25abfefc8ce1.png)
