### ISSUE TITLE
Almacenes--> Rep. Histórica de Artículos: El selector de establecimiento congela pantalla

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-almacenes#16]
**Descripción:**
Cuando se selecciona un establecimiento, sin completar con anterioridad los demás campos, se bugea y la pantalla queda congelada. La única forma de salir de este bug es recargando página.
Además si se completan otros campos, excepto el de la fecha, y se selecciona el Establecimiento, sucede lo mismo.

**Pasos para reproducir:**

1. En Menú seleccionar Almacenes
2. Click en Rep. Histórica de Artículo
3. Seleccionar un establecimiento

https://user-images.githubusercontent.com/87376576/135157523-06a78bd0-0e89-485c-b7ec-086934f90edc.mp4

**Comment by smustafa-trazalog** [comment]
Corregido Versión v1.5.38
