### ISSUE TITLE
Almacenes-->Rep His Artículos: faltan alerts de campos requeridos + modal de carga en loop

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-almacenes#17]
v.1.5.21

**Descripción:**
Cuando se realiza una búsqueda, si se presiona el botón de filtrar sin seleccionar todos los campos requeridos, no muestra el alert de "Complete campos obligatorios"  tampoco es correcto que permita avanzar hacia el filtrado. Posterior al click en "Filtrar" aparece un modal de carga que no desaparece a menos que se recargue la pantalla.

https://user-images.githubusercontent.com/87376576/138123411-1c7bef93-360d-4696-8fe0-bc2fccb91219.mp4

**Comment by smustafa-trazalog** [comment]
Corregido v1.5.38
