### ISSUE TITLE
Soporte AGAL --> Logísitica: Agregar N° de comprobante

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-almacenes#29]
**Descripción:**
En el ingreso de camiones, mostrar número de comprobantes (REMITO).

![image](https://user-images.githubusercontent.com/87376576/142454034-1dc1e5d8-d99b-45a6-a6c6-8e07d691020e.png)

Pasos para reproducir:

1. En menú seleccionar Logística
2. Click en Entrada | Recepción MP
3. Seleccionar Entrada

**Comment by floto-trazalog** [comment]
Se validó la funcionalidad con Mauricio y en conclusión no hace falta agregar dicho campo.
