### ISSUE TITLE
Soporte AGAL --> Reportes --> Ingresos: En el scv exportado, mostrar Nro Batch y "Nro Remito"

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-almacenes#30]
v.1.5.25

Descripción:
Agregar "Nro Batch" y cambiar N° de Bol por "N° Remito (bol)"
<img width="960" alt="reporte de ingreso" src="https://user-images.githubusercontent.com/87376576/145423554-d097d667-6a82-4c33-9554-ff4b5344545b.png">

**Pasos para reproducir:**

1. En el menú Almacenes
2. Dar click en  Reportes
3. Click en Reportes de Ingresos
3. Exportar a Excel

**Comment by floto-trazalog** [comment]
**Descripción:** 
Debe mostrar en la columna ID --> "ID Batch", puesto que hay varios ID en el sistema

![UPS](https://user-images.githubusercontent.com/88331456/146609674-17720ff9-a0ab-40ab-ae50-1104c2758fc5.png)
