### ISSUE TITLE
Almacenes-->Stock: mantener formato de fechas unificado en todo el sistema

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-almacenes#37]
v 1.5.30.3

Descripción:
En la pantalla de stock, las fechas  de filtrado no se ven de acuerdo a lo maquetado. Reemplazar por el formato propuesto a continuación

![image](https://user-images.githubusercontent.com/87376576/145884026-9133ae6f-ba81-48c0-a41f-4f3bdd236b56.png)

**Comment by smustafa-trazalog** [comment]
Sigue sin completar
v1.5.38

![image](https://user-images.githubusercontent.com/98842352/155606802-f0c03e90-9652-48fe-bf93-1f0178a89a6e.png)

**Comment by gnicolia-trazalog** [comment]
Solucionado en V 2.2.18.1
