### ISSUE TITLE
Almacenes-->Stock: agregar el botón de Exportar a PDF

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#40]
**Sugerencia:**
Se recomienda agregar el botón de Exportar a PDF el listado del Stock

![EXPPDF](https://user-images.githubusercontent.com/88331456/149019898-416c65ba-08b3-4fec-b9fa-661c493911d9.png)

_Respetando el formato en todo el módulo Almacenes_ como se observa en esta imagen
![image](https://user-images.githubusercontent.com/88331456/149020058-2de466d2-0391-493b-9946-a593b0dfa1ac.png)

**Pasos para reproducir:**

1. En Almacenes dar click en Stock

**Comment by smustafa-trazalog** [comment]
No corregido. v1.5.38

![image](https://user-images.githubusercontent.com/98842352/155768699-77b295f8-1df6-4342-95fe-c8c349925d62.png)

**Comment by floto-trazalog** [comment]
Se desestima este reporte puesto que no es conveniente porque la tabla es extensa
