### ISSUE TITLE
Almacenes-->Recep. Depósito-->agregar un comentario al usuario & cartel "Ver Detalle" 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#48]
Ambiente Test - v1.5.34
(Ligado al Issue https://github.com/Trazalog/traz-comp-almacenes/issues/11)

**Sugerencia 1:**
Proporcionar al usuario un comentario de guía: "Seleccione el depósito o Nro. de Comprobante" (ubicado arriba de la tabla de remitos)
La idea es que el usuario de click sobre cualquier parte de la fila y el sistema cargue los datos correspondientes a dicho depósito o comprobante

**Sugerencia 2:**
Agregar el cartel "Ver Detalle" al posicionarse sobre el botón de acción "Lupa" 

**Sugerencia 3:**
El ícono para cargar los datos del remito es confuso, se sugiere cambiarlo por el ícono que se adjunta en la misma imagen (con el Nro. **3**)

![MEJORA-31](https://user-images.githubusercontent.com/88331456/151867311-2e5a5d7d-b4a8-4386-8388-1164d190a598.png)

**Pasos para la reproducción:**

1. En Almacenes dar click en Recep. Depósito
2. Completar los datos de "Recepción de Depósito"
3. Dar click en el botón "Buscar"
4. Seleccionar un remito para cargar los datos de la recepción

**Comment by smustafa-trazalog** [comment]
CORREGIDO v1.5.38
![image](https://user-images.githubusercontent.com/98842352/155784416-8a11639c-793d-4d60-a205-f043aa5ea8c7.png)
