### ISSUE TITLE
Almacenes-->Artículos-->Agregar: repite el código de artículo, pero el sistema no avisa 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#50]
Ambiente Producción - v1.5.33.3

**Descripción:**
Al cargar un nuevo artículo el sistema me permite usar el mismo código de uno ya existente y activo, lo ideal sería que notifique con un cartel

**Sugerencia:**
Que se abra una modal mostrando: "Ud. ha ingresado un código repetido, ¿desea continuar? y los botones de "Cancelar y Aceptar"

https://user-images.githubusercontent.com/88331456/152359202-d8d2ac61-98f1-498d-a28c-0b071ead4e2c.mp4

**Pasos para la reproducción:**

1. En Almacenes dar click en Artículos
2. Dar click en el botón "Agregar"
3. Completar los datos repitiendo un código ya existente 
4. Dar click en el botón "Guardar"

**Comment by smustafa-trazalog** [comment]
SIGUE PROBLEMA AL CARGAR UN CODIGO YA INGRESADO, NO AVISA QUE EL CODIGO ESTA REPETIDO

**Comment by smustafa-trazalog** [comment]
CORREGIDO V1.5.38

![image](https://user-images.githubusercontent.com/98842352/155785758-cd7153e3-7876-4eb0-8bbd-9c2176b7a380.png)
