### ISSUE TITLE
Almacenes-->Salida Depósito: actualizar el buscador de artículos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#52]
Ambiente Test - v1.5.35

**Descripción:**
En **Productos a cargar** se recomienda actualizar el campo buscador para unificar las vistas en todo el sistema
Abajo se muestra la vista recomendada

![RECEP-DEP-10](https://user-images.githubusercontent.com/88331456/153444187-24292423-721d-4d38-a2de-a7407c7647d8.png)

_vista recomendada_
![RECEP-DEP-11](https://user-images.githubusercontent.com/88331456/153444439-f39a7706-a0a5-455e-9a14-69dc259ff1c9.png)

**Pasos para reproducir:**

1. En menú Almacenes
2. Dar click en Salida Depósito
3. Completar los datos obligatorios
4. Completar los **Datos del transporte** (opcional)
5. Completar **Productos a Cargar**

**Comment by smustafa-trazalog** [comment]
![image](https://user-images.githubusercontent.com/98842352/154561915-4c725cc4-5cd1-4b7f-a570-4420fa24b304.png)
completado
