### ISSUE TITLE
ALMACÉN --> Ajuste de Stock: No lleno ningún campo, al seleccionar guardar aparece Cartel "Guardado exitosamente"

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-comp-almacenes#53]
v1.5.35

Ambiente test

Descripción:
Al generar un ajuste de stock, se seleccionó únicamente la pestaña de "Tipo de ajuste" seleccionando "robo", el resto de los campos no se modificó. Al seleccionar guardar, indico "guardado exitosamente" sin haber cargado ningún dato previo.
Se deberían agregar campos obligatorios como:

1. llenar *establecimiento (obligatorio)
2. llenar *deposito (obligatorio)
3. llenar *tipo de ajuste (obligatorio)

Sugerencia:

1. debería aparecer pop up si deseo realizar cambios con opción si o no
2. si doy click en guardar sin antes de llenar los campos debería decir "Ingresar datos obligatorios"

https://user-images.githubusercontent.com/98842352/154755584-fbc91b72-f653-4dbd-9676-98719b635c74.mp4

![image](https://user-images.githubusercontent.com/98842352/153071529-c699c84a-1a70-4ad5-b1e4-2d7af47ced46.png)

Pasos a reproducir:
1. Seleccionar modulo almacenes
2. Sección: ajuste de stock
3. lleno solamente datos en casilla de "tipo de ajuste"
4. se habilita panel de salida 
5. No lleno ningún campo
6. doy click en boton guardar
7. Me indica que el ajuste de stock se guardo correctamente.

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.38
