### ISSUE TITLE
Almacenes --> Artículos: en accion eliminar al agregar articulo me indica un subtitulo que dice "editar" no "eliminar"

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-comp-almacenes#57]
v1.5.36

Ambiente test
Descripción: cuando voy a agregar articulo, en la columna acciones, en el icono X para eliminar producto, me indica un comentario que dice editar, debería decir "eliminar"

![Sin título](https://user-images.githubusercontent.com/98842352/153659591-9a2c4912-23bd-47b3-a886-566107325dce.png)

Pasos para reproducir:

En menú seleccionar Almacenes
1. Click en Artículos
2. Click en Agregar
3. Columnas acciones, posicionarse por encima de icono "X", comentario deberia decir "eliminar"

**Comment by smustafa-trazalog** [comment]
![Group 1 (4)](https://user-images.githubusercontent.com/98842352/154545967-bbcbedf3-8614-4764-bf07-7749517b976d.png)

MEJORA: 
> En el diseño adjunto elimine los recuadros negros por encima de las acciones de exportar, 
> reubique el recuadro "mostrar registro" en pagina y subi el cuadro de buscar.
> También sugiero agregar una pantalla que diga desea exportar? en caso que seleccione algunas de las formas de exportación, pdf o excel.

![Group 1 (5)](https://user-images.githubusercontent.com/98842352/154547921-dc725302-e3ee-4824-ba55-b5e655965135.png)

> un cartel que indique que se copiaron los datos en porta papeles

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.38

Nota: la sugerencia de la reubicación de los elementos, no va a ser posible debido a que la ubicación del buscar y la tabla estan predeterminados por la plantilla de tema LTE.
