### ISSUE TITLE
Almacenes-->Rep His Artículos: Al cargar un establecimiento en particular "La marina" modal de carga en loop 

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-comp-almacenes#61]
v1.5.38
ambiente test

Descripción:
Al cargar un establecimiento en particular "La marina" no encuentra el deposito por lo que modal de carga se queda en loop y hay que recargar la pagina para poder seguir navegando. Debería avisar que no tiene un deposito asociado, en caso que ese sea el problema, y volver a la pagina para poder dejar que se siga realizando otra carga.
Este error surge de revisar el issue https://github.com/Trazalog/traz-comp-almacenes/issues/17, el cual se encuentra completado.

https://user-images.githubusercontent.com/98842352/155597343-82cea9f8-fbde-4c17-b70c-dfe216a4a06e.mp4

Pasos para reproducción:
1. Almacenes
2. Rep. Historia de artículos
3. Selecciono establecimiento "la marina" y se queda cargando.

**Comment by floto-trazalog** [comment]
En v2.1.10

Esto sucede a raíz de no encontrar artículos dentro del establecimiento.
