### ISSUE TITLE
Almacenes--> Ajuste de Stock: mostrar el detalle de artículo en el select

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-almacenes#62]
ambiente PROD v2.0.3 

Descripción:
Para facilitarle al usuario la elección de su acción, mostrar el detalle de artículo en el select.
![image](https://user-images.githubusercontent.com/87376576/157693573-6497c665-2790-47ef-9c72-c33c64f080fa.png)

Se sugiere que aparezca el detalle de la cantidad como en este ej
![image](https://user-images.githubusercontent.com/87376576/157694451-f946aa72-502c-4263-9a3a-a1570f2fa8d6.png)

**Comment by floto-trazalog** [comment]
Solucionado antes de v2.0.18.1
Aproximadamente en la v2.0.13.1
