### ISSUE TITLE
Almacenes-->Artículos-->Editar: no permite editar el artículo

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#67]
Ambiente Test - v2.0.7.1

**Descripción:**
Al editar un artículo ya existente, por ejemplo cambiar el Tipo o Descripción el sistema abre una modal de error notificando al usuario que el código ya existe y lo correcto debería ser que permita el cambio

![BugEditar](https://user-images.githubusercontent.com/88331456/160410382-8d064ce7-af3e-46dc-93ab-941d0238ee6e.png)

**Pasos a reproducir:**

1. En el menú Almacenes
2. Dar click en Artículos
3. Dar clcik en el botón de acción "Editar"
4. Modificar Tipo, Descripción o Punto de de pedido
5. Dar click en el botón "Guardar"

**Comment by aalfaro-trazalog** [comment]
Soporte Yudica tambien reportaron esto el 12-05-22 en la v 2.0.12

**Comment by aalfaro-trazalog** [comment]
Solucionado! Funcionando en v 2.1
