### ISSUE TITLE
SOPORTE-->Almacenes-->Pedido Materiales: al crear un pedido no muestra la trazabilidad correcta

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#72]
Ambiente Test - v2.0.8.3
URL: http://10.142.0.16/test/traz-comp-dnato/main/login
User: jperez@prueba.com
Contraseña: 12345

**Descripción:**
Al revisar el detalle de un pedido de materiales el sistema pierde la trazabilidad e inventa un proceso de inicio y fin

https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/79464047-2e48-4d18-97f8-4ed12a65adfb

**Pasos a reproducir:**

1. En el menú Almacenes
2. Click en Pedido Materiales
3. Click en el botón agregar
4. Completar los datos requeridos
5. Click en el botón "Guardar"

**Resultado esperado:**
Se espera ver la trazabilidad correspondiente al pedido de materiales con sus respectivos datos de las actividades 
* **_Actividades Pendientes_**
* _Entrega pedido pendiente_
*  _Fecha Inicio: 27-12-2023 15:58 hs_
* _Usuario: Juan Perez_
* _Descripción:_
* _Duración: 127 días 18 hs_
* _Case: 35046_
* **_Actividades Terminadas_**
*
Se agrega un ejemplo en la imagen:

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/88331456/51bf6c2a-a699-4f04-83a1-f352dd937c4b)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by fhernandez-trazalog** [comment]
#72: Resuelto exitosamente, ahora se puede ver la trazabilidad correspondiente al pedido de materiales con sus respectivos datos de las actividades
