### ISSUE TITLE
Almacenes-->Punto de Pedido: muestra la cantidad en negativo

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#89]
Ambiente test - v2.0.15.1

**Descripción**
La pantalla muestra la cantidad en valores negativos y lo correcto es que las muestre en cero. Se recomienda revisar la prueba con los descuentos

![image](https://user-images.githubusercontent.com/88331456/173608842-ec230976-4d7e-4017-86c3-132f2d4c572c.png)

**Pasos a seguir**
1. Clic en Almacenes
2. Clic en Punto Pedido

**Comment by aalfaro-trazalog** [comment]
La cantidad disponible se muestra en negativo porque se utilizaron mas insumos que el stock neto.
