### ISSUE TITLE
Almacenes-->Artículos: agregar columna de "Tipo de Producto"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#90]
Ambiente test / Producción - v2.0,15.1

**Descripción**
Se recomienda agregar en la pantalla del submódulo "Artículos", la columna de "Tipo de Producto"

![image](https://user-images.githubusercontent.com/88331456/173839707-22692cce-f999-4de2-ae8c-c9dde939d2ba.png)

**Pasos a seguir**
1. En Almacenes
2. Clic en "Artículos"

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado
