### ISSUE TITLE
Almacenes--> Recep depósito: Validar que solo aparezcan los depósitos con permiso

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-comp-almacenes#93]
v 2.0.15.5

Descripción:
Cuando se realiza una recepción de depósito, en el campo de Establecimiento Receptor, sólo deben aparecer los establecimientos a los que tenga acceso el usuario.

![image](https://user-images.githubusercontent.com/87376576/176190667-ad665134-4c4f-462f-8fd4-44309ec0578f.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.4.6
