### ISSUE TITLE
Almacenes--> Ajuste Stock: no guarda el ajuste de stock

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-comp-almacenes#95]
Ambiente test - v2.0.18.1

**Descripción**
Al realizar un ajuste de stock el sistema lanza el mensaje de guardado exitoso pero no muestra el movimiento realizado del artículo 
como se observa en el video 

https://user-images.githubusercontent.com/88331456/181637781-00f9325f-0b47-49b5-a165-e8479a9de6b1.mp4

**Resultado esperado:**
Cuando se trate de un ajuste de...
* Entrada --> el sistema debería sumar la cantidad que ingresa el usuario en el campo "Cantidad" al completar el formulario y guarde el movimiento.
* Salida  --> el sistema debería restar la cantidad que ingresa el usuario en el campo "Cantidad" al completar el formulario y guarde el movimiento.

**Pasos a seguir**
1. Almacenes
2. Ajuste stock
3. Completar los campos
4. Clic en el botón "Guardar"
5. (Revisar dicho movimiento en Almacenes --> Stock)

**Comment by gnicolia-trazalog** [comment]
Continua con el defecto

**Comment by jfernandez-trazalog** [comment]
Rogelio Sanchez.

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.20
